#!/bin/bash
# ----------------------------------------------------------------------
# marc-index
# Adam Wead
# Rock and Roll Hall of Fame and Museum
#
# Description:
#   Puts the current marc recrod search file from Innopac onto our FTP 
#   server, then downloads and indexes it into Blacklight.
#
# ----------------------------------------------------------------------

# ----------------------------------------------------------------------
# Config
# ----------------------------------------------------------------------

# Get variables from our config file
source "bash_config"

# ----------------------------------------------------------------------
# Main
# ----------------------------------------------------------------------

# Delete the old marc file
/bin/rm -f $REMOTEPATH

# Download marc file from innopac to our ftp server.  Wait 20 minutes
# for it to run, check every 30 secs, and kill it if it hasn't finished
# after that
./timeout3 -t 1200 -i 30 ./download > /dev/null
if [ "$?" -gt "0" ]; then
  echo "Expect download script failed or timed out"
  exit 1;
fi

# Copy the marc file for Blacklight
if [ -e $REMOTEPATH ]; then
	/bin/cp -f $REMOTEPATH $LOCALPATH
else
	echo "Marc file failed to download or was not found"
	exit 1;
fi

# Index it into blacklight
source ~/.bash_profile
cd $BLACKLIGHT_APP
export RAILS_ENV=${RAILS_ENV}
rake solr:marc:index MARC_FILE=$LOCALPATH >& $RAKEOUTPUT
if [ "$?" -gt "0" ]; then
  echo "Rake task failed"
  exit 1;
fi

# Check output from SolrMarc for any errors
cat $RAKEOUTPUT
ERRORS=`grep -c "ERROR" $RAKEOUTPUT`
if [ $ERRORS -gt 0 ]; then
  /bin/cat $RAKEOUTPUT
  exit 1;
else
  exit 0;
fi
